name: MyAwesomeApp
options:
  bundleIdPrefix: com.yourcompany
  # Thêm dòng này để ép định dạng về Xcode 15.0 thay vì tự động lấy bản mới nhất
  xcodeVersion: "15.0" 

targets:
  MyAwesomeApp:
    type: application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set Xcode Version
      run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer

    - name: Install XcodeGen
      run: brew install xcodegen

    - name: Generate Xcode Project
      run: xcodegen generate

    - name: Build iOS App
      run: |
        xcodebuild -scheme MyAwesomeApp \
                   -configuration Debug \
                   -sdk iphonesimulator \
                   CODE_SIGNING_ALLOWED=NO \
                   CODE_SIGNING_REQUIRED=NO \
                   clean build
