name: iOS Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install XcodeGen
      run: brew install xcodegen

    - name: Generate Xcode Project
      run: xcodegen generate

    - name: Build iOS App
      run: |
        xcodebuild -project MAPSIOS.xcodeproj \
                   -scheme MAPSIOS \
                   -configuration Debug \
                   -sdk iphonesimulator \
                   CODE_SIGNING_ALLOWED=NO \
                   CODE_SIGNING_REQUIRED=NO \
                   clean build
