name: iOS build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Generate Xcode Project
        run: xcodegen generate

      - name: Build App
        run: |
          xcodebuild -project MAPSIOS.xcodeproj \
                     -scheme MAPSIOS \
                     -sdk iphoneos \
                     -configuration Release \
                     CODE_SIGNING_ALLOWED=NO
